safe:             false
port:             7993
baseurl:          /  # Where GitHub serves the project up from
url:              http://blog.fontawesome.io

source:           src
destination:      _gh_pages
plugins:          src/_plugins

permalink:        pretty
paginate:         5
timezone:         America/New_York
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

title:            Blog Awesome
description:      The Official Font Awesome Blog
author:
  name:           Dave Gandy
  email:          dave@fontawesome.io
  github:
    handle:       davegandy
    url:          http://github.com/davegandy
  twitter:
    handle:       davegandy
    url:          http://twitter.com/davegandy

fontawesome:
  version:        4.2.0
  url:            http://fontawesome.io
  legacy_url:     http://fortawesome.github.com/Font-Awesome/
  twitter:        fontawesome
  tagline:        the iconic font and CSS framework
  github:
    url:          https://github.com/FortAwesome/Font-Awesome
    project:      Font-Awesome
    org:          FortAwesome

bootstrap:
  version:        3.2.0
jquery:
  version:        1.11.1
google_analytics:
  tracking_id:    UA-30136587-1
typekit:
  embed_code:     kja6hqu
